import { createContext, useContext, useEffect, useState, type ReactNode, type FormEvent } from 'react';
import { Link, useNavigate } from '@tanstack/react-router';
import { LayoutDashboard, Building2, Flag, LogOut, ArrowLeft, Eye, EyeOff, Mail, LockKeyhole, RefreshCw, Users, IndianRupee, MessageSquare, BadgeCheck, Clock, ShieldCheck, PanelLeftClose, PanelLeftOpen } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Brand } from './site';
import { api, ApiError, TOKEN_KEY, label, money } from '@/lib/propertysetu';
type Session={token:string;email:string;request:<T>(path:string,options?:RequestInit)=>Promise<T>};
const AdminContext=createContext<Session|null>(null);
export function useAdmin(){const value=useContext(AdminContext); if(!value)throw new Error('Admin session is required.');return value;}
export function AdminLayout({children}:{children:ReactNode}) {
 const [token,setToken]=useState('');const [email,setEmail]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [collapsed,setCollapsed]=useState(false); const navigate=useNavigate();
 function signOut(){localStorage.removeItem(TOKEN_KEY);setToken('');setEmail('');void navigate({to:'/admin'});}
 async function verify(candidate:string){ const user=await api<{is_admin:boolean;email:string}>('/api/me',{},candidate); if(user.is_admin!==true){localStorage.removeItem(TOKEN_KEY);throw new Error('This account is not an admin.');} setToken(candidate);setEmail(user.email||'Administrator'); }
 useEffect(()=>{const saved=localStorage.getItem(TOKEN_KEY);if(!saved){setLoading(false);return;}verify(saved).catch(e=>{localStorage.removeItem(TOKEN_KEY);setError(e.message);}).finally(()=>setLoading(false));},[]);
 async function request<T>(path:string,options:RequestInit={}){try{return await api<T>(path,options,token);}catch(e){if(e instanceof ApiError&&e.status===401)signOut();throw e;}}
 return <div className="admin-shell"><aside className={`admin-sidebar ${collapsed?'admin-collapsed':''}`}><Brand/><div className="text-xs uppercase text-muted-foreground admin-sidebar-label">Workspace</div><nav className="admin-nav" aria-label="Admin navigation"><Link to="/admin" activeOptions={{exact:true}}><LayoutDashboard className="size-4"/><span>Overview</span></Link><Link to="/admin/properties"><Building2 className="size-4"/><span>Properties</span></Link><Link to="/admin/reports"><Flag className="size-4"/><span>Reports</span></Link></nav><div className="admin-sidebar-bottom mt-auto"><Link to="/" className="text-sm text-muted-foreground flex items-center gap-2"><ArrowLeft className="size-4"/><span>Back to website</span></Link></div></aside><div className="admin-main"><header className="admin-topbar"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="admin-collapse-button" title={collapsed?'Expand sidebar':'Collapse sidebar'} aria-label={collapsed?'Expand sidebar':'Collapse sidebar'} onClick={()=>setCollapsed(!collapsed)}>{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}</Button><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-primary"/>Admin workspace</span></div>{token?<div className="flex items-center gap-3"><span className="text-muted-foreground hidden sm:inline">{email}</span><Button variant="ghost" size="icon" title="Sign out" aria-label="Sign out" onClick={signOut}><LogOut/></Button></div>:<Link to="/" className="text-muted-foreground">PropertySetu</Link>}</header><main className="admin-content">{loading?<Status title="Checking your account…" loading/>:token?<AdminContext.Provider value={{token,email,request}}>{children}</AdminContext.Provider>:<Login initialError={error} onLogin={async candidate=>{await verify(candidate);localStorage.setItem(TOKEN_KEY,candidate);void navigate({to:'/admin'});}}/>}</main></div></div>;
}
function Login({initialError,onLogin}:{initialError:string;onLogin:(token:string)=>Promise<void>}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [visible,setVisible]=useState(false);const [error,setError]=useState(initialError);const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api<{token:string;user:{id:string;email:string}}>('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})});await onLogin(result.token);}catch(e){setError(e instanceof Error?e.message:'Unable to sign in.');}finally{setBusy(false);}}return <section className="login-section"><div className="eyebrow text-primary">PropertySetu administration</div><h1>Welcome back.</h1><p className="text-muted-foreground mb-8">Sign in to your admin account.</p><form onSubmit={submit}><div className="field"><label htmlFor="email">Email address</label><input id="email" type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></div><div className="field"><label htmlFor="password">Password</label><div className="password-field"><input id="password" type={visible?'text':'password'} autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password"/><Button type="button" variant="ghost" size="icon" aria-label={visible?'Hide password':'Show password'} onClick={()=>setVisible(!visible)}>{visible?<EyeOff/>:<Eye/>}</Button></div></div>{error&&<div role="alert" className="error-notice">{error}</div>}<Button className="w-full" size="lg" disabled={busy}>{busy?<RefreshCw className="animate-spin"/>:<LockKeyhole/>}{busy?'Signing in…':'Sign in'}</Button></form><Button asChild variant="outline" className="w-full mt-3" size="lg"><Link to="/admin-preview"><Eye/>Preview admin layout</Link></Button><p className="flex items-center justify-center gap-2 text-xs text-muted-foreground mt-6"><ShieldCheck className="size-3"/>Restricted to authorised administrators</p></section>;}
export function Status({title,description,loading=false,retry}:{title:string;description?:string;loading?:boolean;retry?:()=>void}){return <div className="empty-state"><Building2 className={loading?'animate-pulse size-7':'size-7'}/><h3>{title}</h3>{description&&<p>{description}</p>}{retry&&<Button variant="outline" onClick={retry}><RefreshCw/>Try again</Button>}</div>;}
function useAdminData<T>(path:string){const {request}=useAdmin();const [data,setData]=useState<T|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [attempt,setAttempt]=useState(0);useEffect(()=>{let active=true;setLoading(true);setError('');request<T>(path).then(value=>{if(active)setData(value);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return ()=>{active=false;};},[path,attempt]);return {data,setData,error,loading,retry:()=>setAttempt(attempt+1)};}
export function Overview(){const {data,error,loading,retry}=useAdminData<Record<string,number>>('/api/admin/stats');const stats=[['properties','Total properties',Building2],['published','Published',BadgeCheck],['pending_review','Pending review',Clock],['inquiries','Inquiries',MessageSquare],['open_reports','Open reports',Flag],['users','Users',Users],['revenue','Revenue',IndianRupee],['views','Property views',Eye]] as const;return <><h1>Overview</h1><p className="admin-subtitle">A clear view of your marketplace.</p>{loading?<Status title="Loading overview…" loading/>:error?<Status title="Overview unavailable" description={error} retry={retry}/>:data?<div className="stats-grid">{stats.map(([key,title,Icon])=><div className="stat" key={key}><div className="stat-top"><span>{title}</span><Icon/></div><div className="stat-value">{key==='revenue'?money(data[key]??0):(data[key]??0).toLocaleString('en-IN')}</div></div>)}</div>:<Status title="No overview available"/>}</>;}
type Property={id:string;title:string;city:string;owner_name:string;listing_type:string;price:number;status:string;verification_status:string;is_featured:boolean;created_at:string;is_premium?:boolean};
const statuses=['draft','pending_review','published','rejected','sold','rented','expired','archived'];const verifications=['pending','submitted','verified','rejected','active'];
function date(value:string){const parsed=new Date(value);return Number.isNaN(parsed.getTime())?'—':parsed.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});}
export function Properties(){const {request}=useAdmin();const {data,setData,error,loading,retry}=useAdminData<Property[]>('/api/admin/properties');const [search,setSearch]=useState('');const [filter,setFilter]=useState('all');const [saving,setSaving]=useState('');const [actionError,setActionError]=useState('');async function update(row:Property,field:string,value:string|boolean){if(field==='status'&&(value==='rejected'||value==='archived')&&!window.confirm(`${value==='rejected'?'Reject':'Archive'} “${row.title}”?`))return;setSaving(row.id);setActionError('');try{const result=await request<Partial<Property>&{id:string}>(`/api/admin/properties/${encodeURIComponent(row.id)}`,{method:'PATCH',body:JSON.stringify({[field]:value})});setData(previous=>previous?.map(item=>item.id===row.id?{...item,...result}:item)??null);}catch(e){setActionError(e instanceof Error?e.message:'Could not update property.');}finally{setSaving('');}}
const rows=(Array.isArray(data)?data:[]).filter(row=>(filter==='all'||row.status===filter)&&`${row.title} ${row.city} ${row.owner_name}`.toLowerCase().includes(search.toLowerCase()));return <><h1>Properties</h1><p className="admin-subtitle">Review listings and manage publication.</p>{loading?<Status title="Loading properties…" loading/>:error?<Status title="Properties unavailable" description={error} retry={retry}/>:<><div className="table-toolbar"><input className="search-input" aria-label="Search properties" placeholder="Search title, city, or owner" value={search} onChange={e=>setSearch(e.target.value)}/><select className="table-select" aria-label="Filter property status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option>{statuses.map(status=><option key={status} value={status}>{label(status)}</option>)}</select></div>{actionError&&<div role="alert" className="error-notice">{actionError}</div>}{rows.length?<div className="table-wrapper"><table><thead><tr>{['Property','City','Owner','Type','Price','Status','Verification','Featured','Created'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td className="font-semibold">{row.title}</td><td>{row.city}</td><td>{row.owner_name}</td><td>{label(row.listing_type)}</td><td>{money(row.price)}</td><td><select className="table-select" aria-label={`Status for ${row.title}`} value={row.status} disabled={saving===row.id} onChange={e=>void update(row,'status',e.target.value)}>{statuses.map(x=><option value={x} key={x}>{label(x)}</option>)}</select></td><td><select className="table-select" aria-label={`Verification for ${row.title}`} value={row.verification_status} disabled={saving===row.id} onChange={e=>void update(row,'verification_status',e.target.value)}>{verifications.map(x=><option value={x} key={x}>{label(x)}</option>)}</select></td><td><input type="checkbox" aria-label={`Featured ${row.title}`} checked={row.is_featured} disabled={saving===row.id} onChange={e=>void update(row,'is_featured',e.target.checked)}/></td><td>{date(row.created_at)}</td></tr>)}</tbody></table></div>:<Status title={search||filter!=='all'?'No matching properties':'No properties yet'} description="Properties will appear here when owners submit listings."/>}</>}</>;}
type Report={id:string;property_title:string;reason:string;description:string;status:string;created_at:string};const reportStatuses=['pending','reviewing','resolved','dismissed'];
export function Reports(){const {request}=useAdmin();const {data,setData,error,loading,retry}=useAdminData<Report[]>('/api/admin/reports');const [filter,setFilter]=useState('all');const [saving,setSaving]=useState('');const [actionError,setActionError]=useState('');async function update(row:Report,status:string){setSaving(row.id);setActionError('');try{const result=await request<Partial<Report>>(`/api/admin/reports/${encodeURIComponent(row.id)}`,{method:'PATCH',body:JSON.stringify({status})});setData(previous=>previous?.map(item=>item.id===row.id?{...item,...result,status:result.status??status}:item)??null);}catch(e){setActionError(e instanceof Error?e.message:'Could not update report.');}finally{setSaving('');}}const rows=(Array.isArray(data)?data:[]).filter(row=>filter==='all'||row.status===filter);return <><h1>Reports</h1><p className="admin-subtitle">Keep your marketplace safe and trustworthy.</p>{loading?<Status title="Loading reports…" loading/>:error?<Status title="Reports unavailable" description={error} retry={retry}/>:<><div className="table-toolbar"><span className="text-muted-foreground text-sm">{rows.length} reports</span><select className="table-select" aria-label="Filter reports" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All reports</option>{reportStatuses.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></div>{actionError&&<div role="alert" className="error-notice">{actionError}</div>}{rows.length?<div className="table-wrapper"><table><thead><tr>{['Report ID','Property','Reason','Description','Status','Created'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.id}</td><td className="font-semibold">{row.property_title}</td><td>{label(row.reason)}</td><td className="report-description">{row.description||'—'}</td><td><select className="table-select" value={row.status} aria-label={`Status for report ${row.id}`} disabled={saving===row.id} onChange={e=>void update(row,e.target.value)}>{reportStatuses.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></td><td>{date(row.created_at)}</td></tr>)}</tbody></table></div>:<Status title="No reports to show" description="Reports matching this view will appear here."/>}</>}</>;}
