import { useState } from 'react';
import { ArrowUpRight, Search, Heart, CalendarDays, Camera, Wallet, MessageCircle, Check, Plus, Minus, MapPin, House, KeyRound, Building2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { APP_URL } from '@/lib/propertysetu';
const journeys = {
 buyer: { title: 'Not just a property. Your kind of place.', description: 'A quieter neighbourhood. A shorter commute. Room for a growing family. Start with what matters to you.', items: [{ icon:Search, title:'Find your fit', text:'Browse by city, area, price, and property type. Explore nearby listings on the map.' }, { icon:Heart, title:'Keep the possibilities', text:'Save your favourites and return to the places that feel right.' }, { icon:CalendarDays, title:'See it for yourself', text:'Ask the owner a question, chat about the details, or request a visit.' }], action:'Start exploring' },
 owner: { title: 'Your home has a story. Help it find its next chapter.', description: 'Bring your property to people looking for a place like yours, with the details they need to take the next step.', items:[{icon:Camera,title:'Show what makes it special',text:'Add photos, a video, your price, and the location. Give your property a clear introduction.'},{icon:Wallet,title:'Choose your plan',text:'Select a monthly or yearly standard or premium plan, and pay listing fees from your wallet.'},{icon:MessageCircle,title:'Connect directly',text:'Receive inquiries, visit requests, and messages from people interested in your property.'}],action:'List your property' }
};
export function Journey() {
 const [audience,setAudience]=useState<'buyer'|'owner'>('buyer');const content=journeys[audience];
 return <section className="section site-width"><div className="section-heading"><div><div className="eyebrow text-primary">Every move has a story</div><h2>What’s your next move?</h2></div><div className="journey-tabs" role="tablist" aria-label="Your property journey"><Button role="tab" id="buyer-tab" aria-selected={audience==='buyer'} aria-controls="journey-panel" variant={audience==='buyer'?'default':'ghost'} onClick={()=>setAudience('buyer')}><Search/>Find a home</Button><Button role="tab" id="owner-tab" aria-selected={audience==='owner'} aria-controls="journey-panel" variant={audience==='owner'?'default':'ghost'} onClick={()=>setAudience('owner')}><House/>List a home</Button></div></div><div className="journey-layout" id="journey-panel" role="tabpanel" aria-labelledby={`${audience}-tab`}><div className="journey-photo"><img src="/images/hero-viewing.jpg" alt="A couple exploring their next home with an agent" loading="lazy"/><span><MapPin className="size-4"/>A place for new beginnings.</span></div><div className="journey-copy"><h3>{content.title}</h3><p>{content.description}</p><div className="journey-items">{content.items.map(item=><div className="journey-item" key={item.title}><item.icon className="size-5 text-primary"/><div><h4>{item.title}</h4><p>{item.text}</p></div></div>)}</div><Button asChild size="lg"><a href={APP_URL} target="_blank" rel="noopener noreferrer">{content.action}<ArrowUpRight/></a></Button></div></div></section>;
}
const categories=[{id:'buy',title:'A place to own',icon:House,text:'Put down roots. Explore homes for sale and find a place to make your own.',action:'Explore homes for sale'},{id:'rent',title:'Room for right now',icon:KeyRound,text:'A new city or a new routine. Find a rental that fits where life is taking you.',action:'Explore rental homes'},{id:'lease',title:'Space for your plans',icon:Building2,text:'Discover lease listings and connect with owners about the details that matter.',action:'Explore lease listings'},{id:'pg',title:'Your own little corner',icon:MapPin,text:'Browse paying guest options as you settle into a new neighbourhood.',action:'Explore PG options'}];
export function WaysToLive(){const [selected,setSelected]=useState('buy');const current=categories.find(item=>item.id===selected);if(!current)return null;return <section className="ways-band"><div className="site-width section"><div className="section-heading"><div><div className="eyebrow text-primary">Different lives. Different spaces.</div><h2>There’s more than one way home.</h2></div><p>Whatever your next chapter looks like, start with a place that fits.</p></div><div className="category-tabs" role="tablist" aria-label="Property type">{categories.map(item=><Button key={item.id} role="tab" id={`category-${item.id}`} aria-selected={selected===item.id} aria-controls="category-panel" variant={selected===item.id?'default':'outline'} onClick={()=>setSelected(item.id)}><item.icon/>{item.id==='pg'?'PG':item.id.charAt(0).toUpperCase()+item.id.slice(1)}</Button>)}</div><div className="category-panel" role="tabpanel" id="category-panel" aria-labelledby={`category-${selected}`}><div><h3>{current.title}</h3><p>{current.text}</p></div><Button asChild variant="link"><a href={APP_URL} target="_blank" rel="noopener noreferrer">{current.action}<ArrowUpRight/></a></Button></div></div></section>;}
const faqs=[['Can I buy and rent through PropertySetu?','Yes. PropertySetu brings together sale, rent, lease, and PG listings. Browse in the app, save favourites, and connect with the property owner.'],['How do I arrange a property visit?','Open a listing in the app and send a visit request to the owner. You can also enquire or chat to discuss the property before your visit.'],['What do I need to list my property?','Add your property details, location, price, photos, and a video in the app. Choose a standard or premium plan and use your wallet for the listing fee.'],['Are monthly and yearly plans available?','Yes. PropertySetu offers monthly and yearly plans, with standard and premium options. Check the app for the available plans and current prices.'],['Can I use PropertySetu on my iPhone?','Yes. Open app.propertysetu.com in your iPhone browser. Android users can use the Android app. Your account works across the web and Android.'],['Which languages are supported?','PropertySetu supports English, Hindi, and Gujarati.'],['How can I delete my account?','Sign in to the app and open About us to delete your account. This removes your account and the properties you listed.']];
export function Questions(){const [expanded,setExpanded]=useState<number|null>(0);return <section className="section site-width faq-section"><div className="section-heading"><div><div className="eyebrow text-primary">A few things worth knowing</div><h2>Before your next move.</h2></div><p>Clear answers to common questions.</p></div><div className="faq-list">{faqs.map(([question,answer],index)=><div className="faq-item" key={question}><Button variant="ghost" className="faq-trigger" aria-expanded={expanded===index} aria-controls={`answer-${index}`} onClick={()=>setExpanded(expanded===index?null:index)}>{question}{expanded===index?<Minus/>:<Plus/>}</Button><div id={`answer-${index}`} hidden={expanded!==index} className="faq-answer"><p>{answer}</p></div></div>)}</div><div className="privacy-note"><Check className="size-5 text-success"/><p>Your location is only accessed with permission, never in the background. Payment card numbers and UPI PINs are not stored.</p></div></section>;}
